package club.banyuan.project.common.model;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.seat_id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.state
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.created_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.updated_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.seat_id
     *
     * @return the value of order.seat_id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.seat_id
     *
     * @param seatId the value for order.seat_id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.state
     *
     * @return the value of order.state
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.state
     *
     * @param state the value for order.state
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.created_at
     *
     * @return the value of order.created_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.created_at
     *
     * @param createdAt the value for order.created_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.updated_at
     *
     * @return the value of order.updated_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.updated_at
     *
     * @param updatedAt the value for order.updated_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", seatId=").append(seatId);
        sb.append(", userId=").append(userId);
        sb.append(", state=").append(state);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}