package club.banyuan.project.common.model;

import java.io.Serializable;
import java.util.Date;

public class Seat implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.about
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Byte about;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.repair
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Byte repair;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.created_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.updated_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seat
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.id
     *
     * @return the value of seat.id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.id
     *
     * @param id the value for seat.id
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.about
     *
     * @return the value of seat.about
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Byte getAbout() {
        return about;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.about
     *
     * @param about the value for seat.about
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setAbout(Byte about) {
        this.about = about;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.repair
     *
     * @return the value of seat.repair
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Byte getRepair() {
        return repair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.repair
     *
     * @param repair the value for seat.repair
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setRepair(Byte repair) {
        this.repair = repair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.created_at
     *
     * @return the value of seat.created_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.created_at
     *
     * @param createdAt the value for seat.created_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.updated_at
     *
     * @return the value of seat.updated_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.updated_at
     *
     * @param updatedAt the value for seat.updated_at
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat
     *
     * @mbg.generated Tue Jun 23 20:59:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", about=").append(about);
        sb.append(", repair=").append(repair);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}